#pragma once

enum BNS_SKILL_CONDITION
{
	BNS_SKILL_CONDITION_DISTANCE,
	BNS_SKILL_CONDITION_INNERFORCE,
	BNS_SKILL_CONDITION_EVENT,
	BNS_SKILL_CONDITION_MAX
};

enum BNS_SKILL_SLOT
{
	BNS_SKILL_SLOT_LB,
	BNS_SKILL_SLOT_RB,
	BNS_SKILL_SLOT_TAB,
	BNS_SKILL_SLOT_F,
	BNS_SKILL_SLOT_1,
	BNS_SKILL_SLOT_2,
	BNS_SKILL_SLOT_3,
	BNS_SKILL_SLOT_4,
	BNS_SKILL_SLOT_Z,
	BNS_SKILL_SLOT_X,
	BNS_SKILL_SLOT_C,
	BNS_SKILL_SLOT_V,

	BNS_SKILL_SLOT_RENDER_SLOT,
	BNS_SKILL_SLOT_Q = BNS_SKILL_SLOT_RENDER_SLOT,
	BNS_SKILL_SLOT_E,
	BNS_SKILL_SLOT_SS,


	BNS_SKILL_SLOT_MAX
};

enum BNS_ANIMATION_TYPE
{
	BNS_ANIMATION_TYPE_UPPER = 1,
	BNS_ANIMATION_TYPE_LOWER = 2,
	BNS_ANIMATION_TYPE_MAX
};

enum LYN_STATE
{
	LYN_STATE_PEACE_STANDARD = 1,
	LYN_STATE_BATTLE_STANDARD = 2,
	LYN_STATE_BATTLE_HIDEBLADE = 4,
	LYN_STATE_MAX
};

enum LYN_SKILL_STATE
{
	LYN_SKILL_STATE_STANDARD,
	LYN_SKILL_STATE_HIDE,
	LYN_SKILL_STATE_LAY,
	LYN_SKILL_STATE_GROGY,
	LYN_SKILL_STATE_AIR,
	LYN_SKILL_STATE_MAGNETIC,
	LYN_SKILL_STATE_MAX
};

enum LYN_MOVE_DIR_STATE
{
	LYN_MOVE_DIR_STATE_FRONT,
	LYN_MOVE_DIR_STATE_RIGHT,
	LYN_MOVE_DIR_STATE_FRONTRIGHT,
	LYN_MOVE_DIR_STATE_LEFT,
	LYN_MOVE_DIR_STATE_FRONTLEFT,
	LYN_MOVE_DIR_STATE_BACK,
	LYN_MOVE_DIR_STATE_BACKRIGHT,
	LYN_MOVE_DIR_STATE_BACKLEFT,
	LYN_MOVE_DIR_STATE_NONE,
	LYN_MOVE_DIR_STATE_MAX
};

enum BATTLE_STATE
{
	BATTLE_STATE_WEAK, // 
	BATTLE_STATE_ABNORMALSTATE_RESISTANCE, // 상태이상 저항
	BATTLE_STATE_RESISTANCE, // 상태이상 + 피해 저항
	BATTLE_STATE_GROGY,
	BATTLE_STATE_STUN,
	BATTLE_STATE_DOWN,
	BATTLE_STATE_AIR,
	BATTLE_STATE_INVINCIBILITY,
	BATTLE_STATE_DEAD,
	BATTLE_STATE_MAX
};

enum ATTACK_TYPE
{
	ATTACK_TYPE_DEFAULT,
	ATTACK_TYPE_DOWN,
	ATTACK_TYPE_GROGY,
	ATTACK_TYPE_STUN,
	ATTACK_TYPE_MAGNETIC,
	ATTACK_TYPE_AIR,
	ATTACK_TYPE_KNOCKBACK,
	ATTACK_TYPE_MAX
};

enum DAMAGE_FONT_ANIMATION_TYPE
{
	DAMAGE_FONT_ANIMATION_TYPE_FALLING,
	DAMAGE_FONT_ANIMATION_TYPE_EMPHASIS,
	DAMAGE_FONT_ANIMATION_TYPE_MAX
};