#pragma once
#ifndef __NALMAK_ENUM_H__
#define __NALMAK_ENUM_H__

enum DEBUGGING_MODE
{
	DEBUGGING_MODE_FREE_CAMERA_ROCK,
	DEBUGGING_MODE_FREE_CAMERA,
	DEBUGGING_MODE_DEBUG_LOG,
	DEBUGGING_MODE_COLLIDER,
	DEBUGGING_MODE_GIZMO,
	DEBUGGING_MODE_RENDERTARGET,
	DEBUGGING_MODE_PICKING,
	DEBUGGING_MODE_GRID,
	DEBUGGING_MODE_TIME_PAUSE,
	DEBUGGING_MODE_UPDATE_MATERIAL,
	DEBUGGING_MODE_MAX
};

enum VERTEX_INPUT_LAYOUT
{
	VERTEX_INPUT_LAYOUT_POSITION,
	VERTEX_INPUT_LAYOUT_POSITION_UV,
	VERTEX_INPUT_LAYOUT_POSITION_NORMAL_UV,
	VERTEX_INPUT_LAYOUT_SKYBOX,
	VERTEX_INPUT_LAYOUT_PARTICLE,
	VERTEX_INPUT_LAYOUT_POSITION_NORMAL_BINORMAL_TANGENT_UV,
	VERTEX_INPUT_LAYOUT_POSITION_COLOR,
	VERTEX_INPUT_LAYOUT_POSITION_NORMAL_UV_ANIMATIONBLENDING,
	VERTEX_INPUT_LAYOUT_MAX
};

enum MESH_TYPE
{
	MESH_TYPE_VIBUFFER,
	MESH_TYPE_STATIC,
	MESH_TYPE_ANIMATION,
	MESH_TYPE_MAX
};

enum RENDERING_MODE
{
	RENDERING_MODE_BACKGROUND,
	RENDERING_MODE_OPAQUE,
	RENDERING_MODE_CUTOUT,
	RENDERING_MODE_TRANSPARENT,
	RENDERING_MODE_OVERLAY,
	RENDERING_MODE_MAX
};

enum BLENDING_MODE
{
	BLENDING_MODE_DEFAULT,
	BLENDING_MODE_ADDITIVE,
	BLENDING_MODE_SUBTRACTIVE,
	BLENDING_MODE_MULTIPLY,
	BLENDING_MODE_MAX
};

enum TEXTURE_FORMAT
{
	TEXTURE_FORMAT_A16B16G16R16F,
	TEXTURE_FORMAT_D24S8,
	TEXTURE_FORMAT_G32R32F,
	TEXTURE_FORMAT_A32B32G32R32F,
	TEXTURE_FORMAT_A8R8G8B8,
	TEXTURE_FORMAT_MAX,
};

enum DEPTH_STENCIL_FORMAT
{
	DEPTH_STENCIL_FORMAT_D16,
	DEPTH_STENCIL_FORMAT_D24S8,
	DEPTH_STENCIL_FORMAT_D32,
	DEPTH_STENCIL_FORMAT_MAX
};

enum FILL_MODE
{
	FILL_MODE_SOLID,
	FILL_MODE_WIREFRAME,
	FILL_MODE_POINT,
	FILL_MODE_MAX
};

enum LIGHT_MODE
{
	LIGHT_MODE_DIRECTIONAL,
	LIGHT_MODE_POINT,
	LIGHT_MODE_SPOT,
	LIGHT_MODE_MAX
};
enum CAMERA_PROJECTION_MODE
{
	CAMERA_PROJECTION_MODE_PERSPECTIVE,
	CAMERA_PROJECTION_MODE_ORTHOGRAPHIC,
	CAMERA_PROJECTION_MODE_MAX
};

enum CAMERA_RENDERING_MODE
{
	CAMERA_RENDERING_MODE_DEFERRED,
	CAMERA_RENDERING_MODE_FORWARD,
	CAMERA_RENDERING_MODE_MAX
};

enum CAMERA_CLEAR_FLAGS
{
	CAMERA_CLEAR_FLAGS_SOLID,
	CAMERA_CLEAR_FLAGS_SKYBOX,
	CAMERA_CLEAR_FLAGS_DEPTHONLY,
	CAMERA_CLEAR_FLAGS_MAX
};

enum MOUSE_STATE
{
	MOUSE_STATE_LEFT,
	MOUSE_STATE_RIGHT,
	MOUSE_STATE_WHEEL,
	MOUSE_STATE_MAX
};

enum MOUSE_MOVE_STATE
{
	MOUSE_MOVE_STATE_X,
	MOUSE_MOVE_STATE_Y,
	MOUSE_MOVE_STATE_Z,
	MOUSE_MOVE_STATE_MAX
};


enum INTERPOLATION_TYPE
{
	INTERPOLATION_TYPE_ACCELERATE_DECELERTAE,
	INTERPOLATION_TYPE_ACCELERATE,
	INTERPOLATION_TYPE_DECELERATE,
	INTERPOLATION_TYPE_LINEAR,
	INTERPOLATION_TYPE_ANTICIPATE,
	INTERPOLATION_TYPE_OVERSHOOT,
	INTERPOLATION_TYPE_DECELERATE_ACCELERATE
};

enum PARTICLE_EMIT_SHAPE
{
	PARTICLE_EMIT_SHAPE_SPHERE,
	PARTICLE_EMIT_SHAPE_CIRCLE,
	PARTICLE_EMIT_SHAPE_BOX,
	PARTICLE_EMIT_SHAPE_CONE,
	PARTICLE_EMIT_SHAPE_MAX
};

enum PARTICLE_BILLBOARD_TYPE
{
	PARTICLE_BILLBOARD_TYPE_NONE,
	PARTICLE_BILLBOARD_TYPE_DEFAULT,
	PARTICLE_BILLBOARD_TYPE_HORIZONTAL,
	PARTICLE_BILLBOARD_TYPE_VERTICAL,
	PARTICLE_BILLBOARD_TYPE_STERTCHED,
	PARTICLE_BILLBOARD_TYPE_MAX
};
enum COLLIDER_TYPE
{
	COLLIDER_TYPE_SPHERE,
	COLLIDER_TYPE_LINE,
	COLLIDER_TYPE_MAX
};
enum CONSTRAINTS_DIRECTION
{
	CONSTRAINTS_DIRECTION_X,
	CONSTRAINTS_DIRECTION_Y,
	CONSTRAINTS_DIRECTION_Z,
	CONSTRAINTS_DIRECTION_MAX
};

enum CELL_STATE
{
	CELL_STATE_DEFAULT,
	CELL_STATE_INVALID,
	CELL_STATE_OPEN,
	CELL_STATE_MAX
};

enum DEBUG_COLOR
{
	DEBUG_COLOR_RED,
	DEBUG_COLOR_GREEN,
	DEBUG_COLOR_BLUE,
	DEBUG_COLOR_MAX
};

enum BUTTON_TRANSITION
{
	BUTTON_TRANSITION_NONE,
	BUTTON_TRANSITION_COLOR,
	BUTTON_TRANSITION_SWAP,
	BUTTON_TRANSITION_MAX
};

enum BUTTON_STATE
{
	BUTTON_STATE_NORMAL,
	BUTTON_STATE_HIGHLIGHT,
	BUTTON_STATE_PRESSED,
	BUTTON_STATE_DISABLE,
	BUTTON_STATE_MAX
};

enum RENDERER_TYPE
{
	RENDERER_TYPE_MESH,
	RENDERER_TYPE_TRAIL,
	RENDERER_TYPE_CANVAS,
	RENDERER_TYPE_PARTICLE,
	RENDERER_TYPE_SKINNED_MESH,
	RENDERER_TYPE_MAX
};

#endif